FROM mysql:latest

# Change ownership of all files in here
RUN chown -R mysql:root /var/lib/mysql/

ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_ROOT_PASSWORD

ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

COPY /database/sql/data.sql /etc/mysql/data.sql

RUN cp /etc/mysql/data.sql /docker-entrypoint-initdb.d

EXPOSE 3306