version: '3'
services:
  db:
    image: maria-db:latest
    ports:
      - "3306:3306"
  app:
    image: haiku-app:latest
    ports:
      - "4000:4000"
    depends_on:
      - db
    restart: on-failure

# version: '3'
# services:
#   db:
#     build:
#       context: .
#       dockerfile: Dockerfile.db
#     ports:
#       - 3306:3306
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile.app
#     restart: on-failure
#     ports:
#       - 4000:4000