version: '3'
services:
  db:
    image: localhost/maria-db:latest
    ports:
      - "3306:3306"
  app:
    image: localhost/haiku-app-1:latest
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: sh -c "sleep 85 && ./main"