version: '3'
services:
  db:
    image: localhost/maria-db:latest
    ports:
      - "3306:3306"
  app:
    image: localhost/haiku-app:latest
    ports:
      - "4000:4000"
    depends_on:
      - db
    restart: always
    restart_delay: 30s

# version: '3'
# services:
#   db:
#     build:
#       context: .
#       dockerfile: Dockerfile.db
#     ports:
#       - 3306:3306
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile.app
#     restart: always
#     restart_delay: 30s
#     ports:
#       - 4000:4000