version: '3.8'
services:
  db:
    image: localhost/mysql-db:latest
    ports:
      - 3306:3306
  check-db-started: 
    image: jwilder/dockerize:0.6.1
    depends_on:
      - db
    command: 'dockerize -wait=tcp://db:3306'
  app:
    image: localhost/haiku-app:latest
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - check-db-started