package main

import (
	"bytes"
	"io"
	"net/http"
	"net/http/httptest"
	"testing"

	"gotest.tools/v3/assert"
)

func TestPing(t *testing.T) {
	//initialize the httptest.ResponseRecorder
	rr := httptest.NewRecorder()

	//a dummy http Request
	r, err := http.NewRequest(http.MethodGet, "/", nil)
	if err != nil {
		t.Fatal(err)
	}

	//call the ping handler and pass in the ResponseRecorder and Request
	ping(rr, r)

	//get the response generated by the ping handler
	rs := rr.Result()

	//check that staus code recorded was 200
	assert.Equal(t, rs.StatusCode, http.StatusOK)

	//check if response written by ping handler is "OK"
	defer rs.Body.Close()
	body, err := io.ReadAll(rs.Body)
	if err != nil {
		t.Fatal(err)
	}
	bytes.TrimSpace(body)

	assert.Equal(t, string(body), "OK")

}
